### ISSUE TITLE
Auto Fold doesn't auto start with auto opened files

### ISSUE THREAD

**Issue by juanitogan** [fermads/sublime-autofold#4]
If you start Sublime with files already open and don't open any others, Auto Fold doesn't work.  If you resave one of those open files, it still doesn't work.  You have to open another Auto Folded file type or close and reopen one to get it to start working.

This was difficult to figure out why it wasn't working when trying to program new settings (I'm not using this for web types right now).  I thought I just wasn't getting the regex or something else right but, no, I needed to open a triggering file type.

**Comment by fermads** [comment]
Thank you! Looks like a Sublime bug. I fixed with the workaround suggested here:

https://github.com/SublimeTextIssues/Core/issues/5
https://github.com/SublimeTextIssues/Core/issues/1498
